language:
  - go

go:
  - '1.10'

addons:
  firefox: 45.4.0
  apt:
    sources:
     - google-chrome
    packages:
     - google-chrome-stable fluxbox
  sauce_connect: true

services:
  - postgresql
  - xvfb

branches:
  except:
    - /^[0-9]+\.[0-9]+\.[0-9]+$/

script:
  - sudo apt-get install -yq --no-install-suggests --no-install-recommends postgresql-common
  - sudo service postgresql stop
  - sudo apt install -yq --no-install-suggests --no-install-recommends postgresql-11 postgresql-client-11
  - sudo service postgresql start 11

